package com.cds.model;
// Generated 07-06-2019 08:35:56 AM by Hibernate Tools 0.0.1-SNAPSHOT

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias", catalog = "inventario")
public class Categorias implements java.io.Serializable {

	private Long idCategoria ;
	private String nombreCategoria;
	private List<Productos> productos = new ArrayList<Productos>(0);
	
	public Categorias() {
		
	}

	public Categorias(long idCategoria) {
		super();
		this.idCategoria = idCategoria;
	}

	public Categorias(Long idCategoria, String nombreCategoria, List<com.cds.model.Productos> productos) {
		super();
		this.idCategoria = idCategoria;
		this.nombreCategoria = nombreCategoria;
		productos = productos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorias", cascade=CascadeType.ALL)

	public List<Productos> getProductos() {
		return productos;
	}

	public void setProductos(List<Productos> productos) {
		productos = productos;
	}

	@Id
	//@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_categoria")
	public Long getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Long idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "nombre_categoria")
	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}

}
