package com.cds.model;
// Generated 07-06-2019 08:35:56 AM by Hibernate Tools 0.0.1-SNAPSHOT

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entradas generated by hbm2java
 */
@Entity
@Table(name = "entrada", catalog = "inventario")
public class Entradas implements java.io.Serializable {

	private Long idEntrada;
	private Productos productos;
	private long cantidad;


	public Entradas() {
	}

	public Entradas(Long idEntrada, Productos productos, Long cantidad, Date fechaEntrada, Date fechaModificacion) {
		super();
		this.idEntrada = idEntrada;
		this.productos = productos;
		this.cantidad = cantidad;
	}
	
	public Entradas(long idEntrada, long cantidad, long idProducto) {
		super();
		this.idEntrada = idEntrada;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_entrada")
	public Long getIdEntrada() {
		return this.idEntrada;
	}

	public void setIdEntrada(Long idEntrada) {
		this.idEntrada = idEntrada;
	}

	@ManyToOne(fetch = FetchType.EAGER,  cascade=CascadeType.ALL)
	@JoinColumn(name = "id_producto")
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "cantidad")
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

	
}
