package com.cds.model;
// Generated 07-06-2019 08:35:56 AM by Hibernate Tools 0.0.1-SNAPSHOT

import java.util.*;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "inventario")
public class Productos implements java.io.Serializable {

	private Long idProducto ;
	private Categorias categorias;
	private Marcas marcas;
	private String nombreProducto;
	private String presentacion ;
	private long cantidad;
	private List<Entradas> entradas;
	private List<Salidas> salidas;
	private long idMarca ;
	private long idCategoria;
	
	public Productos() {
	}
	
	public Productos(long idProducto) {
		super();
		this.idProducto = idProducto;
	}

	public Productos(Long idProducto, String nombreProducto, String presentacion, Marcas marcas, Categorias categorias) {
		super();
		this.idProducto = idProducto;
		this.nombreProducto = nombreProducto;
		this.presentacion = presentacion;
		this.marcas = marcas;
		this.categorias = categorias;
		
	}

	public Productos(Long idProducto, Categorias categorias, Marcas marcas, String nombreProducto, String presentacion,
			long cantidad, Date fechaRegistro, Date fechaModificacion, List<Entradas> entradas, List<Salidas> salidas) {
		super();
		this.idProducto = idProducto;
		this.categorias = categorias;
		this.marcas = marcas;
		this.nombreProducto = nombreProducto;
		this.presentacion = presentacion;
		this.cantidad = cantidad;
		this.entradas = entradas;
		this.salidas = salidas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productos",  cascade=CascadeType.ALL)

	public List<Entradas> getEntradas() {
		return entradas;
	}

	public void setEntradas(List<Entradas> entradas) {
		this.entradas = entradas;
	}


	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productos",  cascade=CascadeType.ALL)
	public List<Salidas> getSalidas() {
		return salidas;
	}

	public void setSalidas(List<Salidas> salidas) {
		this.salidas = salidas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_producto")
	public Long getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	@JoinColumn(name = "id_categoria")
	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	@ManyToOne(fetch = FetchType.EAGER,  cascade=CascadeType.ALL)
	@JoinColumn(name = "id_marca")
	public Marcas getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Marcas marcas) {
		this.marcas = marcas;
	}

	@Column(name = "nombre_producto")
	public String getNombreProducto() {
		return this.nombreProducto;
	}

	public void setNombreProducto(String nombreProducto) {
		this.nombreProducto = nombreProducto;
	}

	@Column(name = "presentacion")
	public String getPresentacion() {
		return this.presentacion;
	}

	public void setPresentacion(String presentacion) {
		this.presentacion = presentacion;
	}

	@Column(name = "cantidad")
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

}
