package com.cds.model;
// Generated 07-06-2019 08:35:56 AM by Hibernate Tools 0.0.1-SNAPSHOT

import java.util.*;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "inventario")
public class Roles implements java.io.Serializable {

	private Long idRol;
	private String rol ;
	private List<Usuarios> Usuarios;
	
	public Roles () {
	}
	
	public Roles(long idRol) {
		super();
		this.idRol = idRol;
	}

	public Roles(Long idRol, String rol, List<com.cds.model.Usuarios> usuarios) {
		this.idRol = idRol;
		this.rol = rol;
		Usuarios = usuarios;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "roles", cascade=CascadeType.ALL)
	public List<Usuarios> getUsuarios() {
		return Usuarios;
	}

	public void setUsuarios(List<Usuarios> usuarios) {
		Usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_rol")
	public Long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Long idRol) {
		this.idRol = idRol;
	}
	
	@Column(name = "rol")
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}
	

}
