package com.cds.model;
// Generated 07-06-2019 08:35:56 AM by Hibernate Tools 0.0.1-SNAPSHOT

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salidas generated by hbm2java
 */
@Entity
@Table(name = "salidas", catalog = "inventario")
public class Salidas implements java.io.Serializable {

	private Long idSalida ;
	private Productos productos;
	private long cantidad ;
	

	public Salidas() {
	}

	public Salidas(Productos productos, long cantidad, Date fechaSalida, Date fechaModificacion) {
		this.productos = productos;
		this.cantidad = cantidad;
		
	}
	public Salidas(long id,Productos productos, long cantidad, Date fechaSalida, Date fechaModificacion) {
		this.productos = productos;
		this.cantidad = cantidad;
		this.idSalida = id;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_salida")
	public Long getIdSalida() {
		return this.idSalida;
	}

	public void setIdSalida(Long idSalida) {
		this.idSalida = idSalida;
	}

	@ManyToOne(fetch = FetchType.EAGER,  cascade=CascadeType.ALL)
	@JoinColumn(name = "id_producto")
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "cantidad")
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

	
	
}
